# -*- coding: utf-8 -*-
"""Basis, Orthogonal, and Orthonormal Vectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoPj_1VShl7vu8HrVXncFKAncF7HjW7O
"""

import numpy as np

# buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)
i = np.array([1, 0])
i

j = np.array([0, 1])
j

# buktikan bahwa vector i dan vector j itu orthogonal
proof1 = np.dot(i, j)
if proof1 == 0:
  print(f'i dan j adalah orthogonal karena secara matematisnya juga (1, 0) . (0, 1) = (1 x 0) + (0 x 1) = {proof1}')
else:
  print(f'i dan j bukan orthogonal karena hasil akhirnya {proof1}')

# Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?
v = np.array([1, 2])
w = np.array([2, -1])
proof2 = np.dot(v, w)
if proof2 == 0:
  print(f'v dan w juga orthogonal, karena hasil akhirnya: {proof2}')
else:
  print(f'v dan w bukan orthogonal karena hasil akhirnya: {proof2}')