# -*- coding: utf-8 -*-
"""Exercises on Algebra Data Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nz24g4U0f1F3v_rO1BkLBEeZzxfi2I6k
"""

''' selesaikan soal berikut
What is the transpose of this vector?
[25]
[2]
[-3]
[-23]'''

import numpy as np

x = np.array([[25],
      [2],
      [-3],
      [-23]])
x

x_t = x.T
x_t