# -*- coding: utf-8 -*-
"""Matriks Tensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lp2nehoaM9xAR_XNRLFZ3CFYnm0I3NuE
"""

import numpy as np

# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[20, 10, 40], [7, 10, 14]])
X

# tampilkan ukuran dari matrix X
X.shape

# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

#torch
import torch

X_pt = torch.tensor([[20, 10, 40], [7, 10, 14]])
X_pt

X_pt.shape

X_pt[:,0]

X_pt[1,:]

# tensorflow
import tensorflow as tf

X_tf = tf.Variable([[20, 10, 40], [7, 10, 14]])
X_tf

tf.shape(X_tf)

X_tf[:,0]

X_tf[1,:]