# -*- coding: utf-8 -*-
"""Norms and Unit Vector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACRUbIIJ9FlSa2taOl7z0evN7_01V2uT
"""

import numpy as np

# buat vector x dengan ukuran 3x1
x = np.array([[20],
              [10],
              [40]])
x

# menghitung nilai L2 norm dari vector x
(20**2 + 10**2 + 40**2)**(1/2)

# membuat vector v dengan elemen (3,4)
v = np.array([3, 4])
print(f'Vektor asli: {v}')

# menghitung nilai L2 norm dari vector v
norm = np.linalg.norm(v)
print(f'Panjang vektor: {norm}')

# menampilkan unit vector dari vector v
unit_v = v / norm
print(f'Unit vektor: {unit_v}')

# menghitung panjang unit vector dari vector v
print(f'Panjang unit vektor: {np.linalg.norm(unit_v)}')