# -*- coding: utf-8 -*-
"""Scalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAyHtncdVCxtKpGp6Y6XH-ujGVrawLxk
"""

# variable x dan y beserta nilai nya
x = 14
y = 7

# menampilkan tipe data dari x dan y
print(f"Tipe data dari x: {type(x)}")
print(f"Tipe data dari y: {type(y)}")

# menjumlahkan nilai dari variable x dan y
penjumlahan1 = x + y
print(penjumlahan1)

# variable x_float
x_float = 7.5

# menjumlahkan variable x_float dengan y
penjumlahan2 = x_float + y
print(f"Jumlah x float + y:: {penjumlahan2}")

# menampilkan tipe data dari x_float
print(f"Tipe data dari y: {type(x_float)}")

import tensorflow as tf

# variable x_tf dan y_tf beserta nilai skalar nya
x_tf = tf.Variable(25)
y_tf = tf.Variable(50)

# menampilkan tipe data dari x_tf dan y_tf
print(f'Type dari x_tf adalah: {type(x_tf)}')
print(f'Type dari y_tf adalah: {type(y_tf)}')

# menjumlahkan x_tf + y_tf
penjumlahan3 = x_tf + y_tf
print(penjumlahan3)

# variabel x_float_tf
x_float_tf = tf.Variable(3.90)

# menjumlahkan x_float_tf dengan y
y_float_tf = float(y_tf)
penjumlahan4 = x_float_tf + y_float_tf
print(penjumlahan4)

# tampilkan tipe data dari x_float_tf (Tensorflow)
print(f'Type dari x_float_tf adalah: {type(x_float_tf)}')

import torch

# variable x_pt dan y_pt
x_pt = torch.tensor(25)
y_pt = torch.tensor(50)

# menampilkan tipe data dari x_pt dan y_pt
print(f'Type dari x_pt adalah: {type(x_pt)} dengan nilai {x_pt}')
print(f'Type dari y_pt adalah: {type(y_pt)} dengan nilai {y_pt}')

# menjumlahkan x_pt dengan y_pt
penjumlahan5 = x_pt + y_pt
print(penjumlahan5)

# variabel x_float_pt
x_float_pt = torch.tensor(3.90)

penjumlahan6 = x_float_pt + y_pt
print(penjumlahan6)

print(f'Type dari x_float_pt adalah: {type(x_float_pt)} dengan nilai {x_float_pt}')