# -*- coding: utf-8 -*-
"""Vectors and Vector Transposition .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEhfJe8sgTkq88s4WOgMkj2-YywPKmLZ
"""

import numpy as np

# vector x dengan ukuran 3x1
x = np.array([[10],
              [15],
              [20]])
x

# hitung panjang vector x
len(x)

# menampilkan ukuran vector x
x.shape

# menampilkan tipe data dari vector x
type(x)

# akses elemen pertama dari vector x
x[0]

# menampilkan tipe data elemen pertama dari vector x
type(x[0])


# lakukan transpose pada vector x dan simpan pada variabel x_t
x_trans = x.T
x_trans

# menampilkan ukuran dari vector x_t
x_trans.shape

# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[10],
              [15],
              [20]])
y

# menampilkan ukuran dari vector x_t
y.shape

import tensorflow as tf

#
x_tf = tf.Variable([[10],
                    [15],
                    [20]])
x_tf

#
x_tf.shape

#
y_tf = tf.Variable([[10],
                    [15],
                    [20]])
y_tf

#
y_tf.shape

import torch

#
x_pt = torch.tensor([[10],
                    [15],
                    [20]])
x_pt

#
x_pt.shape

#
y_pt = torch.tensor([[10],
                    [15],
                    [20]])
y_pt

#
y_pt.shape